// src/features/user/userSlice.ts
import { createSlice, PayloadAction, createAsyncThunk } from '@reduxjs/toolkit'; // Import createAsyncThunk
import { User, Status } from '../../types'; // Import our defined types
import axios from 'axios'; // Import Axios

// Define the shape of the state for the user slice
interface UserState {
  currentUser: User | null; // The current user object, null if not logged in
  status: Status; // Status of operations (idle, loading, succeeded, failed)
  error: string | null; // Error message if an operation fails
}

const initialState: UserState = {
  currentUser: null, // Start with no user, it will be loaded
  status: 'idle',
  error: null,
};

// --- Async Thunks ---

// createAsyncThunk for fetching user data
export const fetchUser = createAsyncThunk(
  'user/fetchUser', // Action type prefix
  async () => {
    try {
      // Make an HTTP request to load user from the JSON file
      const response = await axios.get<User>('/data/user.json');
      return response.data; // The data will be the payload of the 'fulfilled' action
    } catch (error) {
      if (axios.isAxiosError(error)) {
        throw new Error(error.message || 'Failed to fetch user data');
      }
      throw new Error('An unknown error occurred while fetching user');
    }
  }
);

const userSlice = createSlice({
  name: 'user', // Slice name
  initialState,
  reducers: {
    // This reducer is now primarily for *setting* a user if already available,
    // or if user data comes from an external source (e.g., login form submission, not fetch).
    // We assume the incoming payload *includes* the ID now if it's not generated by fetchUser.
    setUser: (state, action: PayloadAction<User>) => { // Changed type to User (includes id)
      state.currentUser = action.payload;
      state.status = 'succeeded';
      state.error = null;
    },
    // Reducer to clear user data (e.g., on logout)
    clearUser: (state) => {
      state.currentUser = null;
      state.status = 'idle';
      state.error = null;
    },
    // Reducer to update parts of the user profile
    updateUserProfile: (state, action: PayloadAction<Partial<Omit<User, 'id' | 'startBalance'>>>) => {
      if (state.currentUser) {
        state.currentUser = { ...state.currentUser, ...action.payload };
      }
    },
    // Reducer to update the user's startBalance
    updateUserBalance: (state, action: PayloadAction<number>) => {
      if (state.currentUser) {
        state.currentUser.startBalance = action.payload;
      }
    },
    // Removed direct 'userLoading' and 'userFailed' as they are now handled by extraReducers
  },
  // --- Extra Reducers for Async Thunks ---
  extraReducers: (builder) => {
    builder
      // Handle the 'pending' state of the fetchUser thunk
      .addCase(fetchUser.pending, (state) => {
        state.status = 'loading';
        state.error = null;
      })
      // Handle the 'fulfilled' state when user is successfully fetched
      .addCase(fetchUser.fulfilled, (state, action: PayloadAction<User>) => {
        state.status = 'succeeded';
        state.currentUser = action.payload; // Set the user from the fetched data
      })
      // Handle the 'rejected' state if the fetchUser thunk fails
      .addCase(fetchUser.rejected, (state, action) => {
        state.status = 'failed';
        state.error = action.error.message || 'Failed to load user';
        state.currentUser = null; // Clear user on failure
      });
  },
});

// Export action creators
export const {
  setUser, // This can now be used to manually set a user if needed (e.g., from local storage)
  clearUser,
  updateUserProfile,
  updateUserBalance,
} = userSlice.actions;

// Export the default reducer
export default userSlice.reducer;

// Export selectors
export const selectCurrentUser = (state: { user: UserState }) => state.user.currentUser;
export const selectUserStatus = (state: { user: UserState }) => state.user.status;
export const selectUserError = (state: { user: UserState }) => state.user.error;